blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ & í† ë¡  (Discussions)
    url: https://github.com/Project-Guideon/guideon-frontend/discussions
    about: ë²„ê·¸ë‚˜ ê¸°ëŠ¥ ìš”ì²­ì´ ì•„ë‹Œ ì¼ë°˜ì ì¸ ì§ˆë¬¸ì€ ì—¬ê¸°ì„œ í•´ì£¼ì„¸ìš”.